version: '3.8'

services:
  tonmate-production:
    image: ghcr.io/tonmate/tonmate:latest
    container_name: tonmate-production
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy-production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  proxy-production:
    external: true
    name: proxy-production
