import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '../../../lib/auth';
import { prisma } from '../../../lib/db';

// POST /api/knowledge-sources - Create knowledge source from website
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { agentId, url, name, description, maxDepth = 2 } = body;

    // Validate required fields
    if (!agentId || !url || !name) {
      return NextResponse.json(
        { error: 'Agent ID, URL, and name are required' },
        { status: 400 }
      );
    }

    // Verify agent ownership
    const agent = await prisma.agent.findFirst({
      where: {
        id: agentId,
        userId: session.user.id
      }
    });

    if (!agent) {
      return NextResponse.json(
        { error: 'Agent not found' },
        { status: 404 }
      );
    }

    // Create knowledge source
    const knowledgeSource = await prisma.knowledgeSource.create({
      data: {
        agentId,
        name: name.trim(),
        description: description?.trim() || '',
        type: 'website',
        url: url.trim(),
        status: 'processing'
      }
    });

    // TODO: Start website crawling process here
    // For now, we'll create a mock document
    await prisma.document.create({
      data: {
        knowledgeSourceId: knowledgeSource.id,
        title: `${name} - Home Page`,
        content: `Welcome to ${name}. This is sample content from ${url}. In a real implementation, this would be crawled and processed content.`,
        url: url,
        embedding: null // Would be generated by actual embedding service
      }
    });

    // Update status to completed
    await prisma.knowledgeSource.update({
      where: { id: knowledgeSource.id },
      data: { status: 'completed' }
    });

    const updatedSource = await prisma.knowledgeSource.findUnique({
      where: { id: knowledgeSource.id },
      include: {
        documents: true,
        _count: {
          select: { documents: true }
        }
      }
    });

    return NextResponse.json(updatedSource);
  } catch (error) {
    console.error('Error creating knowledge source:', error);
    return NextResponse.json(
      { error: 'Failed to create knowledge source' },
      { status: 500 }
    );
  }
}

// GET /api/knowledge-sources?agentId=... - List knowledge sources for agent
export async function GET(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const agentId = searchParams.get('agentId');

    if (!agentId) {
      return NextResponse.json(
        { error: 'Agent ID is required' },
        { status: 400 }
      );
    }

    // Verify agent ownership
    const agent = await prisma.agent.findFirst({
      where: {
        id: agentId,
        userId: session.user.id
      }
    });

    if (!agent) {
      return NextResponse.json(
        { error: 'Agent not found' },
        { status: 404 }
      );
    }

    const knowledgeSources = await prisma.knowledgeSource.findMany({
      where: { agentId },
      include: {
        _count: {
          select: { documents: true }
        }
      },
      orderBy: { createdAt: 'desc' }
    });

    return NextResponse.json(knowledgeSources);
  } catch (error) {
    console.error('Error fetching knowledge sources:', error);
    return NextResponse.json(
      { error: 'Failed to fetch knowledge sources' },
      { status: 500 }
    );
  }
}
