name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "20.x"
      NEXT_PUBLIC_APP_URL:
        required: true
        type: string
      NEXTAUTH_URL:
        required: true
        type: string
    secrets:
      DATABASE_URL:
        required: true
      NEXTAUTH_SECRET:
        required: true
      JWT_SECRET:
        required: true
      ENCRYPTION_KEY:
        required: true
    outputs:
      test_success:
        description: "Whether tests passed successfully"
        value: ${{ jobs.test.outputs.test_success }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      test_success: ${{ steps.set-output.outputs.test_success }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup test environment
        run: |
          echo '[•] Writing .env file...'
          echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' > .env
          echo 'NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}' >> .env
          echo 'NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}' >> .env
          echo 'JWT_SECRET=${{ secrets.JWT_SECRET }}' >> .env
          echo 'ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}' >> .env
          echo 'NEXT_PUBLIC_APP_URL=${{ vars.NEXT_PUBLIC_APP_URL }}' >> .env
          echo 'NODE_ENV=production' >> .env

      - name: Generate Prisma client
        run: npm run db:generate

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Set output
        id: set-output
        run: echo "test_success=true" >> $GITHUB_OUTPUT
